version: '3'
services:
  app:
    container_name: time-tracking-rewrites
    restart: always
    build: .
    ports:
      - '9003:9003'
    links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - '27017:27017'
